export const ActionTypes = {
    SET_NFTS: 'SET_NFTS',
    SHOW_CATEGORY: 'SHOW_CATEGORY',
    SHOW_ARTCATEGORY: 'SHOW_ARTCATEGORY',
    SELECTED_NFT: 'SELECTED_NFT',
    SET_NEWS_BLOGS: 'SET_NEWS_BLOGS',
    SELECTED_PROFILE: 'SELECTED_PROFILE',

}